library("XML")
library("quantmod")


#Strike ContactName Last Bid Adk Change %Change Volume OI IV
today<-Sys.Date()
wfilename_<-paste("opprice",today,".txt",sep="")

#^RUT
quart<-getQuote("^RUT")
write.table(quart,wfilename_,quote=T,append=T,sep=",")
write("Strike,ContactName,Last,Bid,Ask,Change,%Change,Volume,OI,IV,ExpDate",wfilename_,append=T)
#2015/01/17
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=^RUT&date=1421452800")
expdate<-"2015/01/17"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,append=T,sep=",")
#2015/01/23
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=^RUT&date=1421971200")
expdate<-"2015/01/23"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,append=T,sep=",")
#2015/01/30
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=^RUT&date=1422576000")
expdate<-"2015/01/30"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,append=T,sep=",")
#2015/02/20
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=^RUT&date=1424390400")
expdate<-"2015/02/20"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,append=T,sep=",")
#2015/06/19
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=^RUT&date=1434672000")
expdate<-"2015/06/19"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,append=T,sep=",")

#SPY
quart<-getQuote("SPY")
write.table(quart,wfilename_,quote=T,append=T,sep=",")
#2015/01/17
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=SPY&date=1421452800")
expdate<-"2015/01/17"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,append=T,sep=",")
#2015/01/23
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=SPY&date=1421971200")
expdate<-"2015/01/23"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,append=T,sep=",")
#2015/02/20
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=SPY&date=1424390400")
expdate<-"2015/02/20"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,append=T,sep=",")
#2015/03/20
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=SPY&date=1426809600")
expdate<-"2015/03/20"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,append=T,sep=",")
#2015/04/17
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=SPY&date=1429228800")
expdate<-"2015/04/17"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,append=T,sep=",")
#2015/06/19
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=SPY&date=1434672000")
expdate<-"2015/06/19"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,append=T,sep=",")

#EEM
quart<-getQuote("EEM")
write.table(quart,wfilename_,quote=T,append=T,sep=",")
write("Strike,ContactName,Last,Bid,Ask,Change,%Change,Volume,OI,IV")
#2015/01/17
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=EEM&date=1421452800")
expdate<-"2015/01/17"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,append=T,sep=",")
#2015/01/30
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=EEM&date=1422576000")
expdate<-"2015/01/30"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,append=T,sep=",")
#2015/02/20
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=EEM&date=1424390400")
expdate<-"2015/02/20"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,append=T,sep=",")
#2015/03/20
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=EEM&date=1426809600")
expdate<-"2015/03/20"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,append=T,sep=",")
#2015/06/19
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=EEM&date=1434672000")
expdate<-"2015/06/19"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,append=T,sep=",")

#SLV
quart<-getQuote("SLV")
write.table(quart,wfilename_,quote=T,append=T,sep=",")
write("Strike,ContactName,Last,Bid,Ask,Change,%Change,Volume,OI,IV")
#2015/01/17
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=SLV&date=1421452800")
expdate<-"2015/01/17"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,append=T,sep=",")
#2015/02/20
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=SLV&date=1424390400")
expdate<-"2015/02/20"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,append=T,sep=",")
#2015/03/20
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=SLV&date=1426809600")
expdate<-"2015/03/20"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,append=T,sep=",")
#2015/04/17
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=SLV&date=1429228800")
expdate<-"2015/04/17"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,append=T,sep=",")
#2015/07/17
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=SLV&date=1437091200")
expdate<-"2015/07/17"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,append=T,sep=",")

