library("XML")
library("quantmod")

#Strike ContactName Last Bid Adk Change %Change Volume OI IV
today<-Sys.Date()
wfilename_<-paste("opprice",today,".csv",sep="")

#^RUT
quart<-getQuote("^RUT")
write.table(quart,wfilename_,quote=T,row.names=F,append=T,sep=",")
write("Strike,ContactName,Last,Bid,Ask,Change,%Change,Volume,OI,IV,ExpDate",wfilename_,append=T)
#2015/11/19
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=^RUT&date=1447977600")
expdate<-"2015/11/19"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
#2015/12/18
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=^RUT&date=1450483200")
expdate<-"2015/12/17"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
#2015/12/31
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=^RUT&date=1451520000")
expdate<-"2015/12/31"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
#2016/1/14
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=^RUT&date=1452816000")
expdate<-"2016/1/14"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
#2016/03/17
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=^RUT&date=1458259200")
expdate<-"2016/3/17"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,row.names=F,col.names=F,append=T,sep=",")

#^SPX(^GSPC)
quart<-getQuote("^GSPC")
write.table(quart,wfilename_,quote=T,row.names=F,append=T,sep=",")
write("Strike,ContactName,Last,Bid,Ask,Change,%Change,Volume,OI,IV,ExpDate",wfilename_,append=T)
#2015/11/5
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=^SPX&date=1446768000")
expdate<-"2015/11/6"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
#2015/11/19
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=^SPX&date=1447977600")
expdate<-"2015/11/19"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
#2015/12/3
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=^SPX&date=1449187200")
expdate<-"2015/12/4"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
#2015/12/18
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=^SPX&date=1450483200")
expdate<-"2015/12/17"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
#2015/12/30
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=^SPX&date=1451520000")
expdate<-"2015/12/31"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
#2016/1/14
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=^SPX&date=1452816000")
expdate<-"2016/1/14"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
#2016/1/28
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=^SPX&date=1454025600")
expdate<-"2016/1/29"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
#2016/03/17
tbl_<-readHTMLTable("http://finance.yahoo.com/q/op?s=^SPX&date=1458259200")
expdate<-"2016/3/17"
tbl_[[2]]["ExpDate"]<-expdate
write.table(tbl_[[2]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
tbl_[[3]]["ExpDate"]<-expdate
write.table(tbl_[[3]],wfilename_,row.names=F,col.names=F,append=T,sep=",")
