$(Get-Content ".\\MarketData\Data\ConfigParameters.csv") -replace "edthrpnm","edthrpnm2" | % { $_ -replace "EvalFnc_EvalConvex,1", "EvalFnc_EvalConvex,0" } | Out-File -Filepath .\MarketData\Data\ConfigParameters2.csv -Encoding default 
$(Get-Content ".\\MarketData\Data\ConfigParameters.csv") -replace "edthrpnm","edthrpnm3" | % { $_ -replace "EvalFnc_UseSortinoRatio,1", "EvalFnc_UseSortinoRatio,0" } | Out-File -Filepath .\MarketData\Data\ConfigParameters3.csv -Encoding default
$(Get-Content ".\\MarketData\Data\ConfigParameters.csv") -replace "edthrpnm","edthrpnm4" | Out-File -Filepath .\MarketData\Data\ConfigParameters4.csv -Encoding default
$(Get-Content ".\\MarketData\Data\ConfigParameters.csv") -replace "edthrpnm","edthrpnm5" | % { $_ -replace "EvalFnc_EvalConvex,1", "EvalFnc_EvalConvex,0" } | Out-File -Filepath .\MarketData\Data\ConfigParameters5.csv -Encoding default
$(Get-Content ".\\MarketData\Data\ConfigParameters.csv") -replace "edthrpnm","edthrpnm6" | % { $_ -replace "EvalFnc_UseSortinoRatio,1", "EvalFnc_UseSortinoRatio,0" } | Out-File -Filepath .\MarketData\Data\ConfigParameters6.csv -Encoding default 
#$(Get-Content ".\\MarketData\Data\ConfigParameters.csv") -replace "edthrpnm","edthrpnm7" | % { $_ -replace "EvalFnc_EvalConvex,1", "EvalFnc_EvalConvex,0" } | % { $_ -replace "EvalFnc_UseSortinoRatio,1", "EvalFnc_UseSortinoRatio,0" } | Out-File -Filepath .\MarketData\Data\ConfigParameters7.csv -Encoding default
$(Get-Content ".\\MarketData\Data\ConfigParameters.csv") | % { $_ -replace "EvalFnc_EvalConvex,1", "EvalFnc_EvalConvex,0" } | % { $_ -replace "EvalFnc_UseSortinoRatio,1", "EvalFnc_UseSortinoRatio,0" } | Out-File -Filepath .\MarketData\Data\ConfigParameters1-2.csv -Encoding default
$(Get-Content ".\\MarketData\Data\ConfigParameters.csv") -replace "edthrpnm","edthrpnm7" |  Out-File -Filepath .\MarketData\Data\ConfigParameters7.csv -Encoding default
$(Get-Content ".\\MarketData\Data\ConfigParameters.csv") -replace "edthrpnm","edthrpnm8" | % { $_ -replace "EvalFnc_EvalConvex,1", "EvalFnc_EvalConvex,0" } | Out-File -Filepath .\MarketData\Data\ConfigParameters8.csv -Encoding default
$(Get-Content ".\\MarketData\Data\ConfigParameters.csv") -replace "edthrpnm","edthrpnm7" | % { $_ -replace "EvalFnc_UseSortinoRatio,1", "EvalFnc_UseSortinoRatio,0" } | Out-File -Filepath .\MarketData\Data\ConfigParameters7-2.csv -Encoding default
$(Get-Content ".\\MarketData\Data\ConfigParameters.csv") -replace "edthrpnm","edthrpnm8" | % { $_ -replace "EvalFnc_EvalConvex,1", "EvalFnc_EvalConvex,0" } | % { $_ -replace "EvalFnc_UseSortinoRatio,1", "EvalFnc_UseSortinoRatio,0" } | Out-File -Filepath .\MarketData\Data\ConfigParameters8-2.csv -Encoding default