source('./EGeomBrownMtn.R',encoding = 'UTF-8')
source('./EOpPosStimulations.R',encoding = 'UTF-8')
source('./EOptionOpr.R',encoding = 'UTF-8')
source('./EOptionOprEurop.R',encoding = 'UTF-8')
source('./EVolatility.R',encoding = 'UTF-8')
source('./ERskRtnEval.R',encoding = 'UTF-8')
