```{r setup, echo = FALSE}
library(ggplot2)
library(RQuantLib)
library(plyr)
library(dplyr)
library(knitr)
source('../EOpPosStimulations.R',encoding = 'UTF-8')
```
---
title: "StimResults"
output: html_document
---
```{r echo = FALSE}
#Config File
ConfigFileName_G="ConfigParameters.csv"
DataFiles_Path_G="C:\\Users\\kuby\\edthrpnm\\MarketData\\data\\"

ConfigParameters<-read.table(paste(DataFiles_Path_G,ConfigFileName_G,sep=""),
                             row.names=1, comment.char="#",header=T,stringsAsFactors=F,sep=",")

#Definition
OpType_Put_G=as.numeric(ConfigParameters["OpType_Put_G",1])
OpType_Call_G=as.numeric(ConfigParameters["OpType_Call_G",1])

#File
Underying_Symbol_G=ConfigParameters["Underying_Symbol_G",1]
ResultFiles_Path_G=ConfigParameters["ResultFiles_Path_G",1]

#Evaluatin Table Position start
evalPosStart=as.numeric(ConfigParameters["SimReportPosStart",1])

#Evaluatin Table Position end
evalPosEnd=as.numeric(ConfigParameters["SimReportPosEnd",1])

#Scenario Mode
ScenarioMode=ConfigParameters["SimReportScenarioMode",1]

#Option Chain and Position Data. Here we use UDL_Positions_Pre ---------------
rf<-paste(DataFiles_Path_G,Underying_Symbol_G,"_Positions_Pre.csv",sep="")
opchain<-read.table(rf,header=T,sep=",",stringsAsFactors=FALSE)

##Spreads to be evaluated loaded
rf<-paste(ResultFiles_Path_G,Underying_Symbol_G,"_EvalPosition.csv",sep="")
evalPositions<-read.table(rf,header=F,sep=",",colClasses="numeric")

if(length(evalPositions)>length(opchain$Position)){
  evalPositions %>% distinct() -> evalPositions 
};rm(rf)

# Top n Spreads
evalPositions %>% slice(evalPosStart:evalPosEnd) -> evalPositions

```
##Scenario Table description
```{r echo = TRUE}
# mu_udly sigma_udly mu_iv sigma_iv weight
#    →(Ntrl)  →(Ntrl)  →     auto     w1
#                      ↑     auto     w2
#                      ↓     auto     w3
#    →        ↓        →     auto     w4
#                      ↑     auto     w5
#                      ↓     auto     w6
#    ↓        ↑        →     auto     w7
#                      ↑     auto     w8
#                      ↓     auto     w9
#    ↑        →        →     auto     w10
#                      ↑     auto     w11
#                      ↓     auto     w12
```
##Put Call TYPE Value
```{r echo = FALSE}
cat("TYPE Value :Put",OpType_Put_G," :Call",OpType_Call_G)
```

##Position Vector and Option Chain
```{r echo=FALSE,warning=FALSE,error=FALSE,fig.width=4.7,fig.height=4.2}
for(Counter in evalPosStart:evalPosEnd){
  
  #drawing spread index (here Counter variable)
  cat(Counter," Spread","\n")
  
  #drawing Position Vector
  evaPos<-evalPositions[Counter-evalPosStart+1,1:length(opchain$Position)]
  evaPos<-unlist(evaPos)
  cat(evaPos,sep=",","\n")
  cat("\n")
  
  #drawing Option Chain
  opchain$Position<-unlist(evaPos)
  #getting position by exluding Position==0 row
  opchain %>% dplyr::filter(Position!=0) -> position
  
  #print position
  cat("\n")
  position %>% select(Date,ExpDate,TYPE,Strike,Position,ContactName,UDLY) %>% mutate(TYPE=ifelse(TYPE==OpType_Put_G,"Put","Call")) %>% print()
  
  #loading the model Scenario of Counter index
  fn<-paste(ResultFiles_Path_G,Underying_Symbol_G,ScenarioMode,Counter,sep="")
  load(file=fn)
  #drawing scenario table and its summary result
  modelScenario %>% dplyr::select(-(resdf))  %>% select(weight,min_profit,max_profit,mean_profit,median_profit,profit_sd) -> tmp
  print(tmp);cat("\n")
  data.frame(min_profit=min(tmp$min_profit),max_profit=max(tmp$max_profit),expected_profit=sum(tmp$weight*tmp$mean_profit)) %>%
    print() ;cat("\n")
  rm(tmp)
  
  #API code chunk
  writeIbAPITicket(out_text_file="",thePosition=position,sep=",")
  
  #drawing graph images for each scenario
  for(i in 1:nrow(modelScenario) ){
    resdf<-modelScenario$resdf[[i]]
    cat("Spread: ",Counter,"Scenario ",i,"\n")
    #udly price histgram
    gg <- ggplot(resdf,aes(x=udly))+geom_histogram(alpha=0.7,aes(y=..density..))+geom_density(size=1.0,adjust=0.8,colour="cyan2")+
      geom_point(x=mean(position$UDLY),y=0,size=6.0,width=3.0,colour="lightgreen",pch=4)+
      geom_point(x=mean(resdf$udly),y=0,size=6.0,colour="red",pch=3)+
      geom_point(x=median(resdf$udly),y=0,size=6.0,colour="orange",pch=1)+
      geom_point(x=mean(resdf$udly)+sd(resdf$udly),y=0,size=6.0,colour="darkgrey",pch=2)+
      geom_point(x=mean(resdf$udly)-sd(resdf$udly),y=0,size=6.0,colour="darkgrey",pch=2)
    print(gg)
    
    #payoff function
    gg <- ggplot(resdf,aes(x=udly,y=profit,colour=liqDay))+
      geom_point(alpha=0.5)+
      geom_point(x=mean(position$UDLY),y=0,size=6.0,colour="lightgreen",pch=4)+
      geom_point(x=mean(resdf$udly),y=0,size=6.0,colour="red",pch=3)+
      geom_point(x=median(resdf$udly),y=0,size=6.0,colour="orange",pch=1)+
      geom_point(x=mean(resdf$udly)+sd(resdf$udly),y=0,size=6.0,colour="darkgrey",pch=2)+
      geom_point(x=mean(resdf$udly)-sd(resdf$udly),y=0,size=6.0,colour="darkgrey",pch=2)
    print(gg)
    
    #profit histgram
    gg <- ggplot(resdf,aes(x=profit))+geom_histogram(alpha=0.7,aes(y=..density..))+geom_density(size=1.0,adjust=0.3,colour="cyan2")+
      geom_point(x=0,y=0,size=6.0,width=3.0,colour="lightgreen",pch=4)+
      geom_point(x=mean(resdf$profit),y=0,size=5.0,colour="red",pch=3)+
      geom_point(x=median(resdf$profit),y=0,size=5.0,colour="orange",pch=1)+
      geom_point(x=mean(resdf$profit)+sd(resdf$profit),y=0,size=5.0,colour="darkgrey",pch=2)+
      geom_point(x=mean(resdf$profit)-sd(resdf$profit),y=0,size=5.0,colour="darkgrey",pch=2)
    print(gg)
    }
  }

```

